name: "Install Airbyte CI"
description: "Install Airbyte CI from source or from a binary according to changed files. Pulls the Dagger Engine image according to the dagger version used in airbyte-ci."

inputs:
  airbyte_ci_binary_url:
    description: "URL to airbyte-ci binary"
    required: false
    default: https://connectors.airbyte.com/airbyte-ci/releases/ubuntu/latest/airbyte-ci
  path_to_airbyte_ci_source:
    description: "Path to airbyte-ci source"
    required: false
    default: airbyte-ci/connectors/pipelines
runs:
  using: "composite"
  steps:
    - name: Install Python 3.10
      id: install-python-3-10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        token: ${{ inputs.github_token }}

    - name: Install Airbyte CI from source
      id: install-airbyte-ci-source
      shell: bash
      run: |
        pip install --upgrade pip
        pip install pipx
        pipx ensurepath
        pipx install ${{ inputs.path_to_airbyte_ci_source }}

    - name: Get dagger engine image name
      id: get-dagger-engine-image-name
      shell: bash
      run: |
        dagger_engine_image=$(airbyte-ci --ci-requirements | tail -n 1 | jq -r '.dagger_engine_image')
        echo "dagger_engine_image=${dagger_engine_image}" >> "$GITHUB_OUTPUT"

    - name: Get dagger engine image
      id: get-dagger-engine-image
      uses: ./.github/actions/get-dagger-engine-image
      with:
        dagger_engine_image: ${{ steps.get-dagger-engine-image-name.outputs.dagger_engine_image }}

outputs:
  install_mode:
    description: "Whether Airbyte CI was installed from source or from a binary"
    value: ${{ steps.determine-install-mode.outputs.install-mode }}
  dagger_engine_image_name:
    description: "Dagger engine image name"
    value: ${{ steps.get-dagger-engine-image-name.outputs.dagger_engine_image }}
