name: Dynamically Build Docker Images for Changed Connectors

on:
  pull_request:
    branches: [master]
    paths:
      - "airbyte-integrations/connectors/**"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-changes.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Identify changed connectors
        id: find-changes
        run: |
          # For pull requests, compare the PR base branch to the head branch
          changed_dirs=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^airbyte-integrations/connectors/' | awk -F'/' '{print $1"/"$2"/"$3}' | sort | uniq)

          # Initialize an empty array to hold the list of changed directories
          dirs_array=()
          # Loop through changed directories and add them to the array
          for dir in $changed_dirs; do
            if [[ -d "$dir" ]]; then
              dirs_array+=("${dir#airbyte-integrations/connectors/}")
            fi
          done
          # Convert the array to a JSON string and set it as an output variable
          echo "name=matrix::{\"include\":"$(printf '%s\n' "${dirs_array[@]}" | jq -R . | jq -cs .)"}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./airbyte-integrations/connectors/${{ matrix.include }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.include }}:latest
