name: Dynamically Build Docker Images for Changed Connectors

on:
  pull_request:
    branches: [master]
    paths:
      - "airbyte-integrations/connectors/**"

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-changes.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Identify changed connectors
        id: find-changes
        run: |
          # For pull requests, compare the PR base branch to the head branch
          changed_dirs=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^airbyte-integrations/connectors/' | awk -F'/' '{print $1"/"$2"/"$3}' | sort | uniq)

          # Initialize an empty array to hold the list of changed directories
          dirs_array=()
          # Loop through changed directories and add them to the array
          for dir in $changed_dirs; do
            if [[ -d "$dir" ]]; then
              dirs_array+=("${dir#airbyte-integrations/connectors/}")
            fi
          done
          # Convert the array to a JSON string and set it as an output variable
          echo "name=matrix::{\"include\":"$(printf '%s\n' "${dirs_array[@]}" | jq -R . | jq -cs .)"}" >> $GITHUB_OUTPUT
